title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Connect an LED
  - title: Light an LED
  - title: PWM an LED
