title: Control an LED with a Raspberry Pi Computer
hero_image: images/banner.png
description: Light, blink and pulse and LED with a Raspberry Pi Computer
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Connect an LED
  - title: Light an LED
  - title: Blink an LED
  - title: Pulse an LED
